sudo: false

language: php

php:
    - 5.5
    - 5.6
    - 7.0
    - hhvm

services:
    - mysql

cache:
    directories:
        - $HOME/.composer/cache/files

env:
    - COMPOSER_FLAGS="--prefer-lowest"
    - SYMFONY_VERSION="^2.8.2"
    - SYMFONY_VERSION="^2.8.2" COMPOSER_FLAGS="--prefer-lowest"

matrix:
    fast_finish: true

    allow_failures:
        - php: 7.0
        - php: hhvm

before_install:
    - phpenv config-rm xdebug.ini
    - composer self-update
    - if [ "${SYMFONY_VERSION}" != "" ]; then composer require --no-update "symfony/symfony:${SYMFONY_VERSION}"; fi;

install:
    - composer update ${COMPOSER_FLAGS} --prefer-source

before_script:
  - mysql -e "create database mydatabase;"
  - mysql -e "grant all privileges on mydatabase.* to 'devuser' identified by 'devpass';"

script:
    - vendor/bin/phpunit --colors
