version: '3.7'

services:
    dev_mysql:
        image: mysql:5.7
        platform: linux/amd64
        volumes:
            - mysql-data:/var/lib/mysql
            - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
        restart: always
        environment:
            MYSQL_HOST: '${MYSQL_HOST}'
            MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
            MYSQL_DATABASE: '${MYSQL_DATABASE}'
            MYSQL_USER: '${MYSQL_USER}'
            MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
        ports:
            - '3306:3306'

    symfony:
        build:
            context: ./symfony
            args:
                PHP_VERSION: 8.1
        image: '${COMPOSE_PROJECT_NAME}/${REPOSITORY_NAME}_symfony:${IMAGE_TAG}'
        container_name: '${REPOSITORY_NAME}_symfony'
        hostname: '${REPOSITORY_NAME}-symfony'
        environment:
            MYSQL_HOST: '${MYSQL_HOST}'
            MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
            MYSQL_DATABASE: '${MYSQL_DATABASE}'
            MYSQL_USER: '${MYSQL_USER}'
            MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
        depends_on:
            - dev_mysql
        volumes:
            - symfony-app:/usr/src/symfony

volumes:
    mysql-data: {}
    symfony-app: {}
